"""empty message

Revision ID: 90bce817f286
Revises: 
Create Date: 2023-11-05 20:30:58.471559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bce817f286'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('option')

    # ### end Alembic commands ###
